edition = "2021"

error_on_unformatted = false

group_imports = "One"
reorder_imports = true
imports_granularity = "Crate"

max_width       = 100
comment_width       = 100

reorder_modules = true
unstable_features   = true
wrap_comments       = true