
FROM rustlang/rust:nightly

RUN apt-get update \
    && apt-get install -y protobuf-compiler libprotobuf-dev

RUN curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

RUN cargo binstall cargo-watch --no-confirm

WORKDIR /app

COPY . /app


ENV CARGO_TARGET_DIR=/app/runner/target
# ENV CONFIG_DIR="./config"

ENTRYPOINT ["/app/scripts/docker_entrypoint.sh"]
